### ISSUE TITLE
Doesn't compile on Linux 3.2

### ISSUE THREAD

**Issue by lonestaritaly** [guillaumezin/nvidiabl#27]
make -C /lib/modules/3.2.0/build M=/usr/src/nvidiabl/nvidiabl modules
make[1]: Entering directory `/usr/src/linux-3.2'
CC [M] /usr/src/nvidiabl/nvidiabl/nvidiabl-module.o
/usr/src/nvidiabl/nvidiabl/nvidiabl-module.c:37:3: warning: #warning USE_BACKLIGHT_SUSPEND
CC [M] /usr/src/nvidiabl/nvidiabl/nvidiabl-models.o
/usr/src/nvidiabl/nvidiabl/nvidiabl-models.c:214:41: error: expected ‘)’ before numeric constant
/usr/src/nvidiabl/nvidiabl/nvidiabl-models.c:215:25: error: expected ‘)’ before string constant
make[2]: *** [/usr/src/nvidiabl/nvidiabl/nvidiabl-models.o] Errore 1
make[1]: *** [_module_/usr/src/nvidiabl/nvidiabl] Errore 2
make[1]: Leaving directory`/usr/src/linux-3.2'
make: **\* [modules] Errore 2

I guess something has changed: it was working flawlessly on 3.1.x
